# Autogenerated at 2026-01-24T18:31:59.876084
# Run _flutter_version_update.dart to update.

FLUTTER_URL='https://storage.googleapis.com/flutter_infra_release/releases/'
FLUTTER_WINDOWS_VERSION='3.41.0-0.0.pre'
FLUTTER_WINDOWS_ARCHIVE='beta/windows/flutter_windows_3.41.0-0.0.pre-beta.zip'
FLUTTER_WINDOWS_SHA256='ffeef338045d5b2c7083d52a31272c5cf164a180009323b5ab65743184894fa8'
FLUTTER_LINUX_VERSION='3.41.0-0.0.pre'
FLUTTER_LINUX_ARCHIVE='beta/linux/flutter_linux_3.41.0-0.0.pre-beta.tar.xz'
FLUTTER_LINUX_SHA256='056a3458ac889ca82ff5df7630ae3b88f48be589b9b21750a83dd0ab5719daa9'
FLUTTER_MACOS_VERSION='3.41.0-0.0.pre'
FLUTTER_MACOS_ARCHIVE='beta/macos/flutter_macos_3.41.0-0.0.pre-beta.zip'
FLUTTER_MACOS_SHA256='95408cecb7795f6cfba4197ea61e70b2f788866295a331dea6fec4f115f44347'
