# Autogenerated at 2026-01-24T11:41:40.790720
# Run _flutter_version_update.dart to update.

FLUTTER_URL='https://storage.googleapis.com/flutter_infra_release/releases/'
FLUTTER_WINDOWS_VERSION='3.38.7'
FLUTTER_WINDOWS_ARCHIVE='stable/windows/flutter_windows_3.38.7-stable.zip'
FLUTTER_WINDOWS_SHA256='a47e6d92fe620454318c3553ac8fc9b6da3d8445207f3637146aa74899375cf9'
FLUTTER_LINUX_VERSION='3.38.7'
FLUTTER_LINUX_ARCHIVE='stable/linux/flutter_linux_3.38.7-stable.tar.xz'
FLUTTER_LINUX_SHA256='2d72de31119ccba1421391aa9ab53891a3e4905987a13f8272766ad78e3bbf93'
FLUTTER_MACOS_VERSION='3.38.7'
FLUTTER_MACOS_ARCHIVE='stable/macos/flutter_macos_3.38.7-stable.zip'
FLUTTER_MACOS_SHA256='9b10dfb08f75b5e40476ca646f5caaf08077f3c78e9e0c9272859ac460591f83'
